[all]
master0 ansible_connection=local ip=10.1.1.3 ansible_become=true ansible_become_method=sudo
router0 ansible_host=10.1.1.4 ip=10.1.1.4 ansible_user=vinothg
bench0  ansible_host=10.1.1.5 ip=10.1.1.5 ansible_user=vinothg
worker0 ansible_host=10.1.1.1 ip=10.1.1.1 ansible_user=vinothg
memory0 ansible_host=10.1.1.2 ip=10.1.1.2 ansible_user=vinothg

[kube_control_plane]
master0

[etcd]
master0

[kube_node]
router0
bench0
worker0
memory0

[calico_rr]

[k8s_cluster:children]
kube_control_plane
kube_node
calico_rr

[general-nodes]
master0

[routing-nodes]
router0

[benchmark-nodes]
bench0

[memory-nodes]
worker0

[storage-nodes]
memory0
